/**
 * HTTP client for the piabyss-memo plugin's local sync control plane.
 *
 * The memo cloud-sync engine (Cloudflare R2) lives inside the piabyss-memo
 * plugin — not the Host. The plugin runs a loopback HTTP server
 * (http://127.0.0.1:<PIABYSS_MEMO_SYNC_PORT|18768>) exposing
 * status/test/sync/auto-sync endpoints; these memo.* protocol handlers proxy
 * to it (same pattern as schedule-api.ts ↔ the pi-schedule plugin).
 *
 * R2 credentials never enter the Host or the protocol layer: they are managed
 * by the plugin's config form in Settings → Plugins (pluginLibrary.setEnv) and
 * read by the plugin from its process environment.
 *
 * Loopback control-plane calls deliberately use node:http instead of the
 * global fetch: the Host installs an undici EnvHttpProxyAgent (which proxies
 * 127.0.0.1 when NO_PROXY is unset) and a hand-written httpProxy in
 * settings.json must never intercept the local memo sync API.
 *
 * Auth: every endpoint except GET /api/health requires the
 * `X-Piabyss-Memo-Sync-Token` header. The token lives in
 * `<agentDir>/piabyss/memo/sync-token` (auto-generated by the plugin, 0600)
 * or can be provided via the PIABYSS_MEMO_SYNC_TOKEN env var.
 */
import * as http from "node:http";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

const DEFAULT_MEMO_SYNC_HTTP_PORT = 18768;
const DEFAULT_REQUEST_TIMEOUT_MS = 10_000;
const MAX_RESPONSE_BYTES = 8 * 1024 * 1024;

export type MemoSyncApiOutcome<T> =
  { ok: true; status: number; data: T } | { ok: false; status: number | null; error: string };

/** 对外可见的同步状态（协议层 MemoSyncSettings 的来源；hasSecrets 不外传）。 */
export type MemoSyncStatusPayload = {
  configured: boolean;
  accountId: string;
  bucket: string;
  autoSync: boolean;
  hasSecrets?: boolean;
  lastSyncAt: number | null;
  lastSyncOk: boolean | null;
  lastSyncError: string | null;
};

/** 一次双向同步的统计（与协议 memo.syncNow 的结果同形）。 */
export type MemoSyncStatsPayload = {
  uploadedNotes: number;
  uploadedImages: number;
  downloadedNotes: number;
  downloadedImages: number;
  bytes: number;
  at: number;
};

function memoSyncApiPort(): number {
  const raw = process.env.PIABYSS_MEMO_SYNC_PORT?.trim();
  if (raw) {
    const parsed = Number.parseInt(raw, 10);
    if (Number.isFinite(parsed) && parsed > 0 && parsed < 65_536) return parsed;
  }
  return DEFAULT_MEMO_SYNC_HTTP_PORT;
}

/** Token for the control plane: env var wins, else <agentDir>/piabyss/memo/sync-token. */
function memoSyncApiToken(agentDir: string): string | null {
  const fromEnv = process.env.PIABYSS_MEMO_SYNC_TOKEN?.trim();
  if (fromEnv) return fromEnv;
  const file = join(agentDir, "piabyss", "memo", "sync-token");
  try {
    if (!existsSync(file)) return null;
    const token = readFileSync(file, "utf8").trim();
    return token.length > 0 ? token : null;
  } catch {
    return null;
  }
}

type RawOutcome =
  { ok: true; status: number; body: string } | { ok: false; status: number | null; error: string };

function rawRequest(
  agentDir: string,
  path: string,
  method: "GET" | "POST",
  body: unknown,
  timeoutMs: number,
): Promise<RawOutcome> {
  return new Promise((resolve) => {
    const payload = body === undefined ? null : Buffer.from(JSON.stringify(body), "utf8");
    const headers: Record<string, string | number> = { Accept: "application/json" };
    if (payload !== null) {
      headers["Content-Type"] = "application/json";
      headers["Content-Length"] = payload.length;
    }
    const token = memoSyncApiToken(agentDir);
    if (token) headers["X-Piabyss-Memo-Sync-Token"] = token;

    const request = http.request(
      {
        host: "127.0.0.1",
        port: memoSyncApiPort(),
        path,
        method,
        headers,
        timeout: timeoutMs,
      },
      (response) => {
        const chunks: Buffer[] = [];
        let size = 0;
        response.on("data", (chunk: Buffer) => {
          size += chunk.length;
          if (size > MAX_RESPONSE_BYTES) {
            request.destroy();
            resolve({
              ok: false,
              status: response.statusCode ?? null,
              error: "response too large",
            });
            return;
          }
          chunks.push(chunk);
        });
        response.on("end", () => {
          resolve({
            ok: true,
            status: response.statusCode ?? 0,
            body: Buffer.concat(chunks).toString("utf8"),
          });
        });
        response.on("error", (error: Error) => {
          resolve({ ok: false, status: null, error: error.message });
        });
      },
    );
    request.on("timeout", () => {
      request.destroy();
      resolve({ ok: false, status: null, error: "request timeout" });
    });
    request.on("error", (error: Error) => {
      resolve({ ok: false, status: null, error: error.message });
    });
    if (payload !== null) request.write(payload);
    request.end();
  });
}

async function memoSyncApi<T>(
  agentDir: string,
  path: string,
  method: "GET" | "POST",
  options: { body?: unknown; timeoutMs?: number } = {},
): Promise<MemoSyncApiOutcome<T>> {
  const raw = await rawRequest(
    agentDir,
    path,
    method,
    options.body,
    options.timeoutMs ?? DEFAULT_REQUEST_TIMEOUT_MS,
  );
  if (!raw.ok) return { ok: false, status: raw.status, error: raw.error };
  if (raw.status !== 200) {
    let detail = "";
    try {
      const parsed = JSON.parse(raw.body) as { error?: unknown };
      detail = typeof parsed.error === "string" ? parsed.error : "";
    } catch {
      /* 非 JSON 错误体：细节留在状态码里 */
    }
    return {
      ok: false,
      status: raw.status,
      error: detail || `HTTP ${raw.status}`,
    };
  }
  try {
    return { ok: true, status: raw.status, data: JSON.parse(raw.body) as T };
  } catch {
    return { ok: false, status: raw.status, error: "invalid JSON response" };
  }
}

/** GET /api/status — 同步状态（不含密钥）。 */
export function fetchMemoSyncStatus(
  agentDir: string,
): Promise<MemoSyncApiOutcome<MemoSyncStatusPayload>> {
  return memoSyncApi<MemoSyncStatusPayload>(agentDir, "/api/status", "GET");
}

/** POST /api/test — 用插件当前配置做一次 R2 连接测试（不落盘）。 */
export function testMemoSyncConnection(
  agentDir: string,
): Promise<MemoSyncApiOutcome<{ ok: boolean; error: string | null }>> {
  return memoSyncApi<{ ok: boolean; error: string | null }>(agentDir, "/api/test", "POST", {
    timeoutMs: 30_000,
  });
}

/** POST /api/sync — 立即双向同步，返回统计（可能携带大量图片，走长超时）。 */
export function runMemoSyncNow(
  agentDir: string,
): Promise<MemoSyncApiOutcome<MemoSyncStatsPayload>> {
  return memoSyncApi<MemoSyncStatsPayload>(agentDir, "/api/sync", "POST", {
    timeoutMs: 300_000,
  });
}

/**
 * POST /api/auto-sync — 「备忘录数据有变更」提示：autoSync 开启时插件防抖同步。
 * Fire-and-forget：控制面不可达（插件未加载/未开启）时静默吞掉。
 */
export function pokeMemoAutoSync(agentDir: string): void {
  void memoSyncApi(agentDir, "/api/auto-sync", "POST", { timeoutMs: 2_500 }).catch(() => undefined);
}
